minor changes

diff --git a/.local/bin/nsxiv-url b/.local/bin/nsxiv-url
--- a/.local/bin/nsxiv-url
+++ b/.local/bin/nsxiv-url
@@ -3,7 +3,7 @@
 cache_dir="${TMPDIR:-/tmp}/nsxiv"
 
 die() {
-    [ -n "$1" ] && printf '%s\n' "$*" >&2;
+    [ -n "$1" ] && printf '%s\n' "$*" >&2
     exit 1
 }
 
@@ -22,8 +22,8 @@ trap cleanup EXIT
 [ -d "$cache_dir" ] || mkdir -p -- "$cache_dir" || die
 while [ -n "$1" ]; do
     case "$1" in
-        *://*.*) get_image "$1" ;;
-        *) echo "Invalid url: $1" >&2 ;;
+    *://*.*) get_image "$1" ;;
+    *) echo "Invalid url: $1" >&2 ;;
     esac
     shift
 done
